{% extends main %}
{% block content %}
    {% if($posts->getPosts()[0] && $posts->getPosts()[1]): %}
        <div class="row mb-2">
        {% foreach($posts->getPosts() as $index => $post): %}
            {% if($index == 0 || $index == 1): %}
            <div class="col-md-6 blog-post">
                <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                    <div class="col p-4 d-flex flex-column position-static">
                        <!-- <strong class="d-inline-block mb-2 text-success">{% var_dump($posts->category($post->parentId ?? 0)); %}</strong> -->
                        <h3 class="mb-0">{{ $post->title }}</h3>
                        <div class="mb-1 text-muted">{{ date("F d", strtotime($post->createdAt)); }}</div>
                        <p class="card-text mb-auto">{{ $post->summary }}</p>
                        <a href="#" class="stretched-link">Continue reading...</a>
                    </div>
                    <div class="col-auto d-none d-lg-block">
                        <svg class="bd-placeholder-img" width="200" height="250" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"></rect><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
                    </div>
                </div>
            </div>
            {% endif; %}
        {% endforeach; %}
        </div>
    {% endif; %}
    <div class="row g-5">
        <div class="col-md-8">
            <h3 class="pb-4 mb-4 fst-italic border-bottom">
                From the Firehose
            </h3>

            {% foreach($posts->getPosts() as $index => $post): %}
                {% if($index > 1): %}
                <article class="blog-post">
                    <h2 class="blog-post-title">{{ $post->title }}</h2>
                    <p class="blog-post-meta">{{ date("F d, Y", strtotime($post->createdAt)); }} by <a href="{{ url_from('user', [{{ $post->authorId }}]) }}">{{ $posts->user($post->authorId) }}</a></p>
                    {{ $posts->contents($post->content) }}
                </article>
                {% endif; %}
            {% endforeach; %}
            <nav class="blog-pagination" aria-label="Pagination">
                <a class="btn btn-outline-primary" href="#">Older</a>
                <a class="btn btn-outline-secondary disabled" href="#" tabindex="-1" aria-disabled="true">Newer</a>
            </nav>
        </div>
    </div>
{% endblock %}