{% extends main %}
{% block content %}
    <div class="row m-5">
        <div class="col-lg col-md-8 card p-2">
            <form action="" method="post">
                {% if(self::getErrors()): %}
                <div class="alert alert-danger" role="alert">
                    <strong>{{ self::getErrors() }}</strong>
                </div>
                {% endif; %}
                <div class="form-group">
                    <label for="">Email</label>
                    <input id="email" class="form-control" type="email" name="email" />
                </div>

                <div class="form-group">
                    <label for="">Password</label>
                    <input id="password" class="form-control" type="password" name="password" />
                </div>

                <div class="form-group mt-2">
                    <input type="submit" name="login" value="Submit" class="btn btn-primary">
                </div>
            </form>
        </div>
    </div>
{% endblock %}